name: king worlflow

on:
  pull_request:
    banches:
      - main
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  welcome:
    name: Welcome the user
    runs-on: ubuntu-latest
    steps:
      - name: Run automate
        run: ./automate.sh

  Errand:
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Go and practice linux"



    


